version: '3'

services:
  app:
    container_name: go_app
    depends_on:
      - postgres
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
    volumes:
      - api:/usr/src/app/
    networks:
      - bookstore_app

  postgres:
    image: postgres:latest
    container_name: go_app_postgres
    environment:
      - POSTGRES_USER=${PG_USER}  
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - DATABASE_HOST=${PG_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - bookstore_app

volumes:
  api:
  database_postgres:                  

  # Networks to be created to facilitate communication between containers
networks:
  bookstore_app:
    driver: bridge
